{{- if .Values.backupUpload.active }}
{{- if empty .Values.backupUpload.objectStorageSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backup-zen.objectStorageSecretName" . }}
  labels: {{ include "backup-zen.labels" . | nindent 4 }}
  namespace: {{ include "backup-zen.namespace" . }}
data:
{{- if eq .Values.backupUpload.objectStorageType "AWS_S3" }}
  AWS_ACCESS_KEY_ID: {{ required "Setting Access key is required!" .Values.backupUpload.AWS_S3.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_DEFAULT_REGION: {{ required "Setting Region is required!" .Values.backupUpload.AWS_S3.AWS_DEFAULT_REGION | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "Setting Secret Access key is required!" .Values.backupUpload.AWS_S3.AWS_SECRET_ACCESS_KEY | b64enc }}
  BUCKET_NAME: {{ required "Setting bucket name is required!" .Values.backupUpload.AWS_S3.BUCKET_NAME | b64enc }}
{{- else if eq .Values.backupUpload.objectStorageType "MinIO" }}
  MINIO_ACCESS_KEY_ID: {{ required "Setting Access key is required!" .Values.backupUpload.MINIO.MINIO_ACCESS_KEY_ID | b64enc }}
  MINIO_URL: {{ required "Setting Region key is required!" .Values.backupUpload.MINIO.MINIO_URL | b64enc }}
  MINIO_SECRET_ACCESS_KEY: {{ required "Setting Secret Access key is required!" .Values.backupUpload.MINIO.MINIO_SECRET_ACCESS_KEY | b64enc }}
  BUCKET_NAME: {{ required "Setting bucket name is required!" .Values.backupUpload.MINIO.BUCKET_NAME | b64enc }}
  OBJECT_NAME: {{ required "Setting object name is required!" .Values.backupUpload.MINIO.OBJECT_NAME | b64enc }}
{{ end -}}
type: Opaque
{{ end -}}
{{ end -}}
